"""grpc.aio server for ItemService (RFC-0001 D3, ADR-0002).

Backend serves, analytics dials: this process never makes outbound gRPC
connections and has zero awareness of connected consumers. Runs in the
same process as FastAPI, on its own port (:50051), started/stopped from
the FastAPI lifespan in app.main.
"""

import logging
import os
import sys
import time
from collections.abc import AsyncIterator, Awaitable, Callable

import grpc
from google.protobuf.timestamp_pb2 import Timestamp
from grpc_health.v1 import health, health_pb2, health_pb2_grpc

from app import otel
from app.crud import count_items, list_items
from app.db import AsyncSessionLocal
from app.events import DISCONNECT, ItemEventPayload, broadcaster
from app.metrics import GRPC_SERVER_HANDLED_TOTAL, GRPC_SERVER_HANDLING_SECONDS, GRPC_SERVER_STREAM_MESSAGES_TOTAL

# Generated by `make generate` (a single `python -m grpc_tools.protoc`
# invocation producing python_out + pyi_out + grpc_python_out together --
# grpcio-tools bundles its own protoc, no buf/protoc install needed; see
# root Makefile `generate` target and services/backend/Dockerfile). That
# generated stub's own import is an absolute top-level `from
# devopsdemo.items.v1 import items_pb2` -- grpcio-tools has no option to
# nest it under `app`. Adding proto_gen itself to sys.path (rather than
# importing via `app.proto_gen.devopsdemo...`) keeps this the one and
# only import path: the alternative would load items_pb2 under two
# different module names and fail with a duplicate-file descriptor-pool
# error.
_PROTO_GEN_DIR = os.path.join(os.path.dirname(__file__), "proto_gen")
if _PROTO_GEN_DIR not in sys.path:
    sys.path.insert(0, _PROTO_GEN_DIR)

from devopsdemo.items.v1 import items_pb2, items_pb2_grpc  # noqa: E402

logger = logging.getLogger(__name__)

GRPC_PORT = int(os.getenv("GRPC_PORT", "50051"))
ITEM_SERVICE_FULL_NAME = "devopsdemo.items.v1.ItemService"

_EVENT_TYPE_TO_PROTO = {
    "created": items_pb2.EVENT_TYPE_CREATED,
    "updated": items_pb2.EVENT_TYPE_UPDATED,
    "deleted": items_pb2.EVENT_TYPE_DELETED,
}


def _event_to_proto(event: ItemEventPayload) -> items_pb2.ItemEvent:
    event_time = Timestamp()
    event_time.FromDatetime(event.event_time)
    return items_pb2.ItemEvent(
        event_type=_EVENT_TYPE_TO_PROTO[event.event_type],
        item=items_pb2.Item(id=event.item_id, name=event.item_name),
        event_time=event_time,
    )


class ItemServiceServicer(items_pb2_grpc.ItemServiceServicer):
    async def ListItems(self, request: items_pb2.ListItemsRequest, context: grpc.aio.ServicerContext) -> items_pb2.ListItemsResponse:
        async with AsyncSessionLocal() as db:
            items = await list_items(db)
        return items_pb2.ListItemsResponse(items=[items_pb2.Item(id=i.id, name=i.name) for i in items])

    async def GetItemStats(self, request: items_pb2.GetItemStatsRequest, context: grpc.aio.ServicerContext) -> items_pb2.GetItemStatsResponse:
        async with AsyncSessionLocal() as db:
            total = await count_items(db)
        return items_pb2.GetItemStatsResponse(total_items=total)

    async def WatchItemEvents(self, request: items_pb2.WatchItemEventsRequest, context: grpc.aio.ServicerContext) -> AsyncIterator[items_pb2.ItemEvent]:
        queue = broadcaster.subscribe()
        try:
            while True:
                event = await queue.get()
                if event is DISCONNECT:
                    logger.info("WatchItemEvents: subscriber disconnected (slow consumer)")
                    return
                yield _event_to_proto(event)
        finally:
            broadcaster.unsubscribe(queue)


class _RedMetricsInterceptor(grpc.aio.ServerInterceptor):
    """RED metrics for every RPC (RFC-0001 D6): rate + errors via
    grpc_server_handled_total, duration via grpc_server_handling_seconds.
    Streaming RPCs are measured over their whole subscribe-to-disconnect
    lifetime; per-message counts go to grpc_server_stream_messages_total.
    """

    async def intercept_service(
        self,
        continuation: Callable[[grpc.HandlerCallDetails], Awaitable[grpc.RpcMethodHandler]],
        handler_call_details: grpc.HandlerCallDetails,
    ) -> grpc.RpcMethodHandler | None:
        handler = await continuation(handler_call_details)
        if handler is None:
            return None
        method = handler_call_details.method.rsplit("/", 1)[-1]

        if handler.unary_unary is not None:
            inner_unary = handler.unary_unary

            async def unary_unary_wrapper(request, context):
                start = time.perf_counter()
                # asyncio.CancelledError is a BaseException, not caught by
                # `except Exception` below -- initialize here so a client
                # cancel mid-call still has a `code` to record in `finally`
                # instead of raising UnboundLocalError.
                code = grpc.StatusCode.OK
                try:
                    response = await inner_unary(request, context)
                    code = context.code() or grpc.StatusCode.OK
                    return response
                except Exception:
                    code = context.code() or grpc.StatusCode.UNKNOWN
                    raise
                finally:
                    GRPC_SERVER_HANDLING_SECONDS.labels(method).observe(time.perf_counter() - start)
                    GRPC_SERVER_HANDLED_TOTAL.labels(method, code.name).inc()

            return grpc.unary_unary_rpc_method_handler(
                unary_unary_wrapper,
                request_deserializer=handler.request_deserializer,
                response_serializer=handler.response_serializer,
            )

        if handler.unary_stream is not None:
            inner_stream = handler.unary_stream

            async def unary_stream_wrapper(request, context):
                start = time.perf_counter()
                # Same reasoning as unary_unary_wrapper above: a client
                # cancelling WatchItemEvents mid-stream (the designed
                # termination path, not an error) raises CancelledError,
                # which `except Exception` does not catch -- initialize
                # `code` before `try` so `finally` never sees it unbound.
                code = grpc.StatusCode.OK
                try:
                    async for response in inner_stream(request, context):
                        GRPC_SERVER_STREAM_MESSAGES_TOTAL.labels(method).inc()
                        yield response
                    code = context.code() or grpc.StatusCode.OK
                except Exception:
                    code = context.code() or grpc.StatusCode.UNKNOWN
                    raise
                finally:
                    GRPC_SERVER_HANDLING_SECONDS.labels(method).observe(time.perf_counter() - start)
                    GRPC_SERVER_HANDLED_TOTAL.labels(method, code.name).inc()

            return grpc.unary_stream_rpc_method_handler(
                unary_stream_wrapper,
                request_deserializer=handler.request_deserializer,
                response_serializer=handler.response_serializer,
            )

        # ItemService has no client-streaming RPC (stream_unary/stream_stream);
        # nothing in this contract exercises that path, so it passes through
        # unwrapped rather than guessing at metrics semantics for it.
        return handler


async def build_grpc_server() -> grpc.aio.Server:
    """Construct and wire the server (ItemService + health), but do not
    bind a port or start it -- split out from start_grpc_server() so
    tests can bind an ephemeral port instead of the fixed GRPC_PORT."""
    # otel interceptor first (D11): outermost, so trace context (W3C
    # metadata extraction) is established before the metrics interceptor
    # runs. See app.otel.grpc_server_interceptor for why this is a plain
    # interceptor rather than GrpcAioInstrumentorServer.instrument().
    server = grpc.aio.server(interceptors=[otel.grpc_server_interceptor(), _RedMetricsInterceptor()])
    items_pb2_grpc.add_ItemServiceServicer_to_server(ItemServiceServicer(), server)

    health_servicer = health.aio.HealthServicer()
    health_pb2_grpc.add_HealthServicer_to_server(health_servicer, server)
    # Kept simple (RFC-0001 D6 handoff): overall + ItemService SERVING as
    # soon as the process is up. DB-down granularity already exists on the
    # HTTP side (/readyz); duplicating it into gRPC health is not done here.
    await health_servicer.set("", health_pb2.HealthCheckResponse.SERVING)
    await health_servicer.set(ITEM_SERVICE_FULL_NAME, health_pb2.HealthCheckResponse.SERVING)
    return server


async def start_grpc_server() -> grpc.aio.Server:
    """Build, bind GRPC_PORT, and start the gRPC server. Caller stops it
    via `await server.stop(grace)` (see app.main lifespan)."""
    server = await build_grpc_server()
    server.add_insecure_port(f"[::]:{GRPC_PORT}")
    await server.start()
    logger.info(f"gRPC server listening on :{GRPC_PORT}")
    return server
