[security]
# Disable password change requirement on first login
disable_initial_admin_password_change = true
# Disable Gravatar
disable_gravatar = true

[users]
# Disallow registration of new users
allow_sign_up = false
# Disallow organization creation
allow_org_create = false
# Disallow password update via UI (for admin)
allow_update_password = true
