---
{{ include "common.serviceaccount" . }}
---
{{ include "common.pvc" . }}
---
{{ include "common.configmap" . }}
---
{{ include "common.secret" . }}
---
{{ include "common.fileconfigmap" . }}
---
{{ include "common.statefulset" . }}
---
{{ include "common.service" . }}
