name: Frontend

on:
  pull_request:
    paths:
      - "services/frontend/**"
      - ".github/workflows/frontend.yml"
  push:
    branches:
      - main
    paths:
      - "services/frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: services/frontend/.nvmrc
          cache: "npm"
          cache-dependency-path: services/frontend/package-lock.json

      - name: Install dependencies
        working-directory: services/frontend
        run: |
          npm ci

      - name: Run ESLint
        run: |
          make lint-frontend

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: services/frontend/.nvmrc
          cache: "npm"
          cache-dependency-path: services/frontend/package-lock.json

      - name: Install dependencies
        working-directory: services/frontend
        run: |
          npm ci

      - name: Run tests
        run: |
          make test-frontend
